#pragma once

#define COMMISSION_FEE  0.01
#define DAILY_LIMIT_RSD 50000

#define ACCOUNT_PREFIX_UUID "ACC"
#define CLIENT_PREFIX_UUID "CLI"
#define CREDIT_PREFIX_UUID "CRE"
#define TRANSACTION_PREFIX_UUID "TRA"
